#!/bin/bash
set -euo pipefail

. "$HOME"/repo/.venv/bin/activate

COMMON="-dir:"$HOME"/repo -log:recent-vios.log"
PAGE="User:Wcam-bot/report/NFCC_violations/recent"
QUERY=$(cat <<EOF
select distinct
  p1.page_namespace,
  p1.page_title
from
  linktarget lt1
  left join categorylinks cl on lt1.lt_id = cl.cl_target_id
  left join page p1 on cl.cl_from = p1.page_id
  left join linktarget lt2 on p1.page_namespace = lt2.lt_namespace and p1.page_title = lt2.lt_title
  left join imagelinks il on lt2.lt_id = il.il_target_id
  left join page p2 on il.il_from = p2.page_id
  left join recentchanges rc on rc.rc_title = p2.page_title and rc.rc_namespace = p2.page_namespace
where
  lt1.lt_namespace = 14
  and lt1.lt_title = '所有非自由媒體'
  and cl.cl_type = 'file'
  and p1.page_namespace = 6
  and lt2.lt_namespace = 6
  and rc.rc_bot = 0
  and rc.rc_source in ('mw.edit', 'mw.new')
  and $(date -ud '-5 hours' +'%Y%m%d%H%M%S') <= rc.rc_timestamp;
EOF
)

nfcbot list-vios $COMMON -mysqlquery:"$QUERY" $PAGE

nfcbot nfur-fixer $COMMON -ns:6 -links:$PAGE --always

#nfcbot remove-vios $COMMON -ns:not:6 -links:$PAGE --always
